### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by tarunm97** [AmoabaKelvin/Medium-Anti-Member-Only#6]
Getting this Error when trying to open a link

<img width="657" alt="Screenshot 2023-08-08 at 11 15 39" src="https://github.com/AmoabaKelvin/Medium-Anti-Member-Only/assets/64698451/3a6264da-4d23-45af-9b8b-e60ff395c2cb">

**Comment by AmoabaKelvin** [comment]
Thank you soo much for pointing this out. 
Will work on this ASAP and get back to you. 

If I may ask, what browser do you use?

**Comment by tarunm97** [comment]
Chrome
