### ISSUE TITLE
12fi.io is not working now

### ISSUE THREAD

**Issue by ZhymabekRoman** [AmoabaKelvin/Medium-Anti-Member-Only#7]
Hello everyone. Unfortunately, sites that allow you to bypass paid articles like 12ft.io no longer work, Medium has changed the logic of how they generate access. After some thought, I decided to write my own site that would allow you to read Medium articles for free. I called it Freedium. Unfortunately not everything works properly, but for the most part it should work, if you find any bugs please PM me, or you can contribute to the code as it's completely open source: https://freedium.cfd

**Comment by AmoabaKelvin** [comment]
Thanks @ZhymabekRoman 
Thank you very much for bringing this to notice and sharing your wonderful project. I’ll do well to contribute to it.

**Comment by AmoabaKelvin** [comment]
If you can share the link to the repo under this thread, it will be great

**Comment by ZhymabekRoman** [comment]
Yes of course: https://github.com/Freedium-cfd

**Comment by Welding-Torch** [comment]
@ZhymabekRoman I've been looking for a tool like this for months now! Thank you so much for making this.
